import Head from "next/head";
import { useRouter } from "next/router";

import BtnLink from "@/Buttons/BtnLink";
import Hero from "@/pageComponents/index/Hero";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Crickets Studio / 404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero title="404">
          <div className="btn-group">
            <BtnLink onClick={() => router.push("/")}>Home</BtnLink>
          </div>
        </Hero>
      </main>
    </>
  );
}
