import Head from "next/head";

import Hero from "@/pageComponents/index/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Crickets Studio / Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero title="Crickets Studio" />
      </main>
    </>
  );
}
